import type { Deck } from './types'

export const sampleDeck: Deck = {
  id: 'sample',
  title: '操作確認',
  extractedAt: '2026-10-08T00:00:00.000Z',
  tokenCount: 48,
  coveredTokens: 44,
  limit: 6,
  episodes: [{ id: 'scene1', title: 'scene1', tokenCount: 48 }],
  cards: [
    {
      id: 'sample:miss',
      lemma: 'miss',
      pos: 'verb',
      count: 3,
      episodeCount: 1,
      episodes: ['scene1'],
      gloss: '逃す、乗り遅れる',
      example: 'I missed the last train.',
      kind: 'word',
    },
    {
      id: 'sample:quiet',
      lemma: 'quiet',
      pos: 'adjective',
      count: 2,
      episodeCount: 1,
      episodes: ['scene1'],
      gloss: '静かな',
      example: 'The station was quiet.',
      kind: 'word',
    },
    {
      id: 'sample:return',
      lemma: 'return',
      pos: 'verb',
      count: 2,
      episodeCount: 1,
      episodes: ['scene1'],
      gloss: '戻る',
      example: 'She promised to return before dark.',
      kind: 'word',
    },
    {
      id: 'sample:bridge',
      lemma: 'bridge',
      pos: 'noun',
      count: 2,
      episodeCount: 1,
      episodes: ['scene1'],
      gloss: '橋',
      example: 'The river moved under the bridge.',
      kind: 'word',
    },
    {
      id: 'sample:promise',
      lemma: 'promise',
      pos: 'verb',
      count: 1,
      episodeCount: 1,
      episodes: ['scene1'],
      gloss: '約束する',
      example: 'She promised to return before dark.',
      kind: 'word',
    },
    {
      id: 'sample:station',
      lemma: 'station',
      pos: 'noun',
      count: 1,
      episodeCount: 1,
      episodes: ['scene1'],
      gloss: '駅',
      example: 'The station was quiet.',
      kind: 'word',
    },
    {
      id: 'sample:mira',
      lemma: 'mira',
      pos: 'proper',
      count: 4,
      episodeCount: 1,
      episodes: ['scene1'],
      gloss: '人の名前',
      example: 'Mira waited by the bridge.',
      kind: 'term',
    },
  ],
}
